export declare const E2BIG: number;
export declare const EACCES: number;
export declare const EADDRINUSE: number;
export declare const EADDRNOTAVAIL: number;
export declare const EAFNOSUPPORT: number;
export declare const EAGAIN: number;
export declare const EALREADY: number;
export declare const EBADF: number;
export declare const EBADMSG: number;
export declare const EBUSY: number;
export declare const ECANCELED: number;
export declare const ECHILD: number;
export declare const ECONNABORTED: number;
export declare const ECONNREFUSED: number;
export declare const ECONNRESET: number;
export declare const EDEADLK: number;
export declare const EDESTADDRREQ: number;
export declare const EDOM: number;
export declare const EDQUOT: number;
export declare const EEXIST: number;
export declare const EFAULT: number;
export declare const EFBIG: number;
export declare const EHOSTUNREACH: number;
export declare const EIDRM: number;
export declare const EILSEQ: number;
export declare const EINPROGRESS: number;
export declare const EINTR: number;
export declare const EINVAL: number;
export declare const EIO: number;
export declare const EISCONN: number;
export declare const EISDIR: number;
export declare const ELOOP: number;
export declare const EMFILE: number;
export declare const EMLINK: number;
export declare const EMSGSIZE: number;
export declare const EMULTIHOP: number;
export declare const ENAMETOOLONG: number;
export declare const ENETDOWN: number;
export declare const ENETRESET: number;
export declare const ENETUNREACH: number;
export declare const ENFILE: number;
export declare const ENOBUFS: number;
export declare const ENODATA: number;
export declare const ENODEV: number;
export declare const ENOENT: number;
export declare const ENOEXEC: number;
export declare const ENOLCK: number;
export declare const ENOLINK: number;
export declare const ENOMEM: number;
export declare const ENOMSG: number;
export declare const ENOPROTOOPT: number;
export declare const ENOSPC: number;
export declare const ENOSR: number;
export declare const ENOSTR: number;
export declare const ENOSYS: number;
export declare const ENOTCONN: number;
export declare const ENOTDIR: number;
export declare const ENOTEMPTY: number;
export declare const ENOTSOCK: number;
export declare const ENOTSUP: number;
export declare const ENOTTY: number;
export declare const ENXIO: number;
export declare const EOPNOTSUPP: number;
export declare const EOVERFLOW: number;
export declare const EPERM: number;
export declare const EPIPE: number;
export declare const EPROTO: number;
export declare const EPROTONOSUPPORT: number;
export declare const EPROTOTYPE: number;
export declare const ERANGE: number;
export declare const EROFS: number;
export declare const ESPIPE: number;
export declare const ESRCH: number;
export declare const ESTALE: number;
export declare const ETIME: number;
export declare const ETIMEDOUT: number;
export declare const ETXTBSY: number;
export declare const EWOULDBLOCK: number;
export declare const EXDEV: number;
declare const Signals: {
    E2BIG: number;
    EACCES: number;
    EADDRINUSE: number;
    EADDRNOTAVAIL: number;
    EAFNOSUPPORT: number;
    EAGAIN: number;
    EALREADY: number;
    EBADF: number;
    EBADMSG: number;
    EBUSY: number;
    ECANCELED: number;
    ECHILD: number;
    ECONNABORTED: number;
    ECONNREFUSED: number;
    ECONNRESET: number;
    EDEADLK: number;
    EDESTADDRREQ: number;
    EDOM: number;
    EDQUOT: number;
    EEXIST: number;
    EFAULT: number;
    EFBIG: number;
    EHOSTUNREACH: number;
    EIDRM: number;
    EILSEQ: number;
    EINPROGRESS: number;
    EINTR: number;
    EINVAL: number;
    EIO: number;
    EISCONN: number;
    EISDIR: number;
    ELOOP: number;
    EMFILE: number;
    EMLINK: number;
    EMSGSIZE: number;
    EMULTIHOP: number;
    ENAMETOOLONG: number;
    ENETDOWN: number;
    ENETRESET: number;
    ENETUNREACH: number;
    ENFILE: number;
    ENOBUFS: number;
    ENODATA: number;
    ENODEV: number;
    ENOENT: number;
    ENOEXEC: number;
    ENOLCK: number;
    ENOLINK: number;
    ENOMEM: number;
    ENOMSG: number;
    ENOPROTOOPT: number;
    ENOSPC: number;
    ENOSR: number;
    ENOSTR: number;
    ENOSYS: number;
    ENOTCONN: number;
    ENOTDIR: number;
    ENOTEMPTY: number;
    ENOTSOCK: number;
    ENOTSUP: number;
    ENOTTY: number;
    ENXIO: number;
    EOPNOTSUPP: number;
    EOVERFLOW: number;
    EPERM: number;
    EPIPE: number;
    EPROTO: number;
    EPROTONOSUPPORT: number;
    EPROTOTYPE: number;
    ERANGE: number;
    EROFS: number;
    ESPIPE: number;
    ESRCH: number;
    ESTALE: number;
    ETIME: number;
    ETIMEDOUT: number;
    ETXTBSY: number;
    EWOULDBLOCK: number;
    EXDEV: number;
};
export { Signals };
